// src/renderer/components/table/delete/table.delete.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { BaseComponent } from '@renderer/app/base.component';
import { ConfigModel } from '@renderer/model/config.model';
import { DatabaseModel } from '@renderer/model/database.model';
import { RequestModel } from '@renderer/model/request.model';
import { DatasourceService } from '@renderer/services/management/datasource.service';
import { TableService } from '@renderer/services/management/table.service';
import { NzMessageService } from 'ng-zorro-antd/message';

@Component({
    selector: 'app-component-delete-table',
    templateUrl: './table.delete.component.html'
})
export class DeleteTableComponent extends BaseComponent {
    @Input()
    config: ConfigModel;
    @Input()
    value: string;
    @Input()
    database: string;
    @Output()
    emitter = new EventEmitter<any>();
    inputValue: string;

    constructor(private dataSourceService: DatasourceService,
        private tableService: TableService,
        private messageService: NzMessageService) {
        super();
    }

    handlerValidate() {
        if (this.inputValue === this.value) {
            this.disabled.button = false;
        } else {
            this.disabled.button = true;
        }
    }

    handlerDelete() {
        this.loading.button = true;
        const request = new RequestModel();
        request.config = this.dataSourceService.getAll(this.config.value)?.data?.columns[0];
        const _value = new DatabaseModel();
        _value.database = this.database;
        _value.name = this.value;
        this.tableService.delete(request, _value).then(response => {
            if (response.status) {
                this.messageService.success(response.message);
                this.emitter.emit(true);
            } else {
                this.messageService.error(response.message);
            }
            this.loading.button = false;
        });
    }
}

<div>
    <em>We don't recommend that you delete the data table
        <nz-tag [nzColor]="'#2db7f5'">{{value}}</nz-tag>
        ? This operation produces the following?
    </em>
    <ol>
        <li>
            <nz-tag [nzColor]="'#f50'">No rollback</nz-tag>
            The metadata will be removed from the Clickhouse metadata
        </li>
        <li>
            <nz-tag [nzColor]="'#f50'">No rollback</nz-tag>
            All data files generated in this table will be removed from the relevant Clickhouse server file system
        </li>
        <li>If you want to confirm the deletion, enter the table name in the
            <input nz-input [(ngModel)]="inputValue" (change)="handlerValidate()" />
            and click the delete button below
        </li>
    </ol>
</div>
<div class="ant-modal-footer" style="padding: 10px;margin-bottom: -20px;margin-top: 20px;">
    <div class="ng-star-inserted">
        <button nz-button nzType="primary" nzDanger [disabled]="disabled.button" [nzLoading]="loading.button"
            (click)="handlerDelete()">
            <span>{{'common.delete'|translate}}</span>
        </button>
    </div>
</div>

// src/renderer/views/components/table/TableDelete.vue
<template>
  <el-dialog
      :title="this.stringFormat('{0} {1}', [this.$t('common.delete'), this.$t('common.table')])"
      :visible.sync="bodyLoading"
      @close="closeDialog">
    <em>We don't recommend that you delete the data table
      <el-tag type="info" size="mini">{{ deleteTable }}</el-tag>
      ? This operation produces the following?</em>
    <ol>
      <li>
        <el-tag type="danger" size="mini">No rollback</el-tag>
        The metadata will be removed from the Clickhouse metadata
      </li>
      <li>
        <el-tag type="danger" size="mini">No rollback</el-tag>
        All data files generated in this table will be removed from the relevant Clickhouse server file system
      </li>
      <li>If you want to confirm the deletion, enter the table name in the
        <el-input v-model="inputDeleteTable" size="mini"></el-input>
        and click the delete button below
      </li>
    </ol>
    <div slot="footer" class="dialog-footer">
      <el-button @click="bodyLoading = false" size="mini">{{ this.$t('common.cancel') }}</el-button>
      <el-button type="danger" size="mini" @click="handlerDeleteTable" :loading="buttonLoading">
        {{ this.$t('common.delete') }}
      </el-button>
    </div>
  </el-dialog>
</template>

<script>
import { deleteTable } from '@/services/Table'

export default {
  name: 'DeleteTable',
  props: {
    loading: {
      type: Boolean,
      default: false
    },
    server: {
      type: String,
      default: ''
    },
    table: {
      type: String,
      default: ''
    },
    database: {
      type: String,
      default: ''
    }
  },
  created() {
  },
  data() {
    return {
      bodyLoading: false,
      remoteServer: null,
      deleteTable: null,
      inputDeleteTable: null,
      remoteDatabase: null,
      buttonLoading: false
    }
  },
  methods: {
    async handlerDeleteTable() {
      this.buttonLoading = true
      if (this.remoteServer === null) {
        this.$notify.error({
          title: 'Error',
          message: 'Remote Server must null!'
        })
        this.buttonLoading = false
        return
      }
      if (this.deleteTable !== this.inputDeleteTable) {
        this.$notify.error({
          title: 'Error',
          message: this.stringFormat('The table <{0}> to be deleted is inconsistent with the target table <{1}>', [this.inputDeleteTable, this.deleteTable])
        })
        this.buttonLoading = false
        return
      }
      const response = await deleteTable(this.remoteServer, this.remoteDatabase, this.inputDeleteTable)
      if (!response.status) {
        this.$notify.error({
          title: this.$t('common.error'),
          message: response.message
        })
      } else {
        this.$notify.success({
          title: this.$t('common.success'),
          message: response.message
        })
        this.closeDialog()
      }
      this.buttonLoading = false
    },
    closeDialog() {
      this.$emit('close')
    }
  },
  watch: {
    loading: {
      deep: true,
      handler() {
        this.bodyLoading = this.loading
      }
    },
    server: {
      deep: true,
      handler() {
        this.remoteServer = this.server
      }
    },
    table: {
      deep: true,
      handler() {
        this.deleteTable = this.table
      }
    },
    database: {
      deep: true,
      handler() {
        this.remoteDatabase = this.database
      }
    }
  }
}
</script>
